name: portal_module
description: A Module
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fpdart: ^1.1.0
  shimmer: ^3.0.0

  # Localization
  intl: ^0.18.1

  ## State Management
  flutter_bloc: ^8.1.3

  ## Navigation
  go_router: ^11.1.2

  ## DI
  get_it: ^7.6.0
  injectable: ^2.3.2

  ## Data / Model class
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  ## Networking
  dio: ^5.4.3+1

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.3.3
  freezed: ^2.4.1
  json_serializable: ^6.6.2
  injectable_generator:
  mockito: ^5.4.2

flutter:
  uses-material-design: true

flutter_gen:
  integrations:
    flutter_svg: true

dependency_overrides:
  intl: ^0.18.0


